import type { PublicProfile, PublicRepository, ProviderResult, WebsiteMetadata } from '../../types';
import { withHealth } from '../github/health';

/**
 * Demo mode. When DEMO_MODE=true, providers return synthetic data that is
 * ALWAYS labelled isDemo=true so the UI can badge it "DEMO".
 * Demo data never represents real people.
 */

const DEMO_PROFILE: PublicProfile = {
  platform: 'github',
  username: 'demo-dev',
  displayName: 'Demo Developer',
  avatarUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=demodev',
  bio: 'Synthetic demo profile generated by DevTrace demo mode. Not a real person.',
  profileUrl: 'https://github.com/github',
  websiteUrl: 'https://example.dev',
  location: 'Demo City',
  followers: 120,
  following: 45,
  publicProjectCount: 3,
  outboundLinks: ['https://example.dev', 'https://www.linkedin.com/in/demo-developer'],
  isDemo: true,
};

const DEMO_REPOSITORIES: PublicRepository[] = [
  withHealth({
    platform: 'github',
    name: 'demo-portfolio',
    description: 'Synthetic demo repository — a portfolio site (demo mode).',
    url: 'https://github.com/github',
    owner: 'demo-dev',
    language: 'TypeScript',
    stars: 42,
    forks: 7,
    openIssues: 2,
    topics: ['demo', 'portfolio', 'react'],
    license: 'MIT',
    homepage: 'https://example.dev',
    isDemo: true,
  }),
  withHealth({
    platform: 'github',
    name: 'demo-ml-toolkit',
    description: 'Synthetic demo repository — machine learning utilities (demo mode).',
    url: 'https://github.com/github',
    owner: 'demo-dev',
    language: 'Python',
    stars: 128,
    forks: 21,
    openIssues: 5,
    topics: ['demo', 'python', 'machine-learning'],
    license: 'Apache-2.0',
    isDemo: true,
  }),
];

const DEMO_WEBSITE: WebsiteMetadata = {
  url: 'https://example.dev',
  finalUrl: 'https://example.dev',
  title: 'Demo Developer — Portfolio (DEMO DATA)',
  description: 'Synthetic demo website metadata. Not a real person.',
  favicon: 'https://api.dicebear.com/7.x/identicon/svg?seed=demodev',
  previewUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
  socialLinks: ['https://github.com/github', 'https://www.linkedin.com/in/demo-developer'],
  githubLinks: ['https://github.com/github'],
  linkedinLinks: ['https://www.linkedin.com/in/demo-developer'],
  technologyHints: ['React', 'Tailwind CSS'],
  siteType: 'portfolio',
  isDemo: true,
};

export function demoGithubResult(query: string): ProviderResult {
  return {
    provider: 'github',
    status: 'FOUND',
    note: `Demo mode is enabled — showing synthetic data for "${query}".`,
    profiles: [{ ...DEMO_PROFILE, username: DEMO_PROFILE.username }],
    repositories: DEMO_REPOSITORIES,
    durationMs: 120,
  };
}

export function demoGitlabResult(query: string): ProviderResult {
  return {
    provider: 'gitlab',
    status: 'FOUND',
    note: `Demo mode synthetic data for "${query}".`,
    profiles: [
      {
        platform: 'gitlab',
        username: 'demo-dev',
        displayName: 'Demo Developer',
        avatarUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=demogitlab',
        bio: 'Synthetic demo profile (demo mode).',
        profileUrl: 'https://gitlab.com/gitlab-org',
        publicProjectCount: 2,
        isDemo: true,
      },
    ],
    durationMs: 90,
  };
}

export function demoNpmResult(): ProviderResult {
  return {
    provider: 'npm',
    status: 'FOUND',
    note: 'Demo mode synthetic data.',
    packages: [
      {
        name: 'demo-trace-lib',
        version: '1.0.0',
        description: 'Synthetic demo npm package (demo mode).',
        url: 'https://www.npmjs.com/package/react',
        author: 'Demo Developer',
      },
    ],
    durationMs: 80,
  };
}

export function demoWebsiteResult(): WebsiteMetadata {
  return { ...DEMO_WEBSITE };
}